M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu20.04.1} date lun 12 sep 2022 10:32:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-12T10:32:02-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.000
%
G90
G05
T1
X17.8Y-18.0
X88.4Y-18.2
X88.4Y-87.6
T0
M30
